# Generated by Django 4.1.5 on 2023-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_bresilienne'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bresilienne',
            new_name='Indienne',
        ),
    ]
