# Generated by Django 4.1.5 on 2023-02-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_rename_bresilienne_indienne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indienne',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='category',
        ),
    ]
